keys:
  - &vishnu age15hlj4ar3y5twk0vql0euhe6s9ah0suwdnep8majkkefllxpkedns27t3m0
  - &ayats_gen6 age14u2cyhdlpf6zuvew6aq0k2y5rsvzzsgvs39p8n0dqftktmm73d2shzktn8

creation_rules:
  - path_regex: secrets(/|\\).*sumati.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6

  - path_regex: secrets(/|\\).*kalypso.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6

  - path_regex: secrets(/|\\).*vault.yaml$
    key_groups:
    - age:
      - *ayats_gen6

  - path_regex: secrets(/|\\)env.yaml$
    key_groups:
    - age:
      - *ayats_gen6

  - path_regex: secrets(/|\\).*shiva.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6

  - path_regex: secrets(/|\\).*lets-encrypt.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6

  - path_regex: secrets(/|\\).*golden.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6

  - path_regex: secrets(/|\\).*tailscale.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6
      - *vishnu

  - path_regex: secrets(/|\\).*chandra.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6

  - path_regex: secrets(/|\\).*vishnu.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6
      - *vishnu
