keys:
  - &sumati age1dnmwd637md9tpwqkj5608skuu583w02xmex9lg4k5dyx3c8eef8qhmqf33
  - &ayats_gen6 age1dvuqf497ljdjd8v6r9w26zlqfv409chfu0txuk48vtglx3sfqa9sd3fnks


creation_rules:
  - path_regex: secrets/.*sumati.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6
      - *sumati
