keys:
  - &shiva age1gzx7nwzldswnslnapup9ust8k57wy6zlg49p47zz972auxhcmfxq9whe6h
  - &ayats_gen6 age14u2cyhdlpf6zuvew6aq0k2y5rsvzzsgvs39p8n0dqftktmm73d2shzktn8

creation_rules:
  - path_regex: secrets(/|\\)env.yaml$
    key_groups:
    - age:
      - *ayats_gen6

  - path_regex: secrets(/|\\).*shiva.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6
      - *shiva

  - path_regex: secrets(/|\\).*tailscale.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6
      - *shiva
