keys:
  - &shiva age1gzx7nwzldswnslnapup9ust8k57wy6zlg49p47zz972auxhcmfxq9whe6h
  - &vishnu age15hlj4ar3y5twk0vql0euhe6s9ah0suwdnep8majkkefllxpkedns27t3m0
  - &ayats_gen6 age14u2cyhdlpf6zuvew6aq0k2y5rsvzzsgvs39p8n0dqftktmm73d2shzktn8
  - &ayats_zorah age15qe0fp9ys9qhmwypznwcl0sw946wkqsd60wlepw5jsfcwq7rl37q7m9g7v

creation_rules:
  #-- Services
  - path_regex: secrets(/|\\)env.yaml$
    key_groups:
    - age:
      - *ayats_gen6
      - *ayats_zorah

  - path_regex: secrets(/|\\).*vault.yaml$
    key_groups:
    - age:
      - *ayats_gen6
      - *vishnu

  - path_regex: secrets(/|\\).*nomad.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6
      - *shiva

  - path_regex: secrets(/|\\).*lets.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6
      - *shiva

  - path_regex: secrets(/|\\)obsidian\.yaml$
    key_groups:
    - age:
      - *ayats_gen6
      - *shiva

  - path_regex: secrets(/|\\)matrix.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6
      - *shiva
      - *ayats_zorah

  - path_regex: secrets(/|\\)mail.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6
      - *shiva

  #-- Hosts
  - path_regex: secrets(/|\\).*shiva.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6
      - *shiva

  - path_regex: secrets(/|\\).*vishnu.*\.yaml$
    key_groups:
    - age:
      - *ayats_gen6
      - *vishnu
