[formatter.nix]
command = "alejandra"
includes = ["*.nix"]
excludes = ["generated.nix"]

[formatter.python3]
command = "black"
includes = ["*.py"]
options = ["--line-length", "79"]

[formatter.hcl]
command = "hclfmt"
includes = ["*.nomad", "*.hcl", "*.tf"]

# [formatter.sh]
# command = "shfmt"
# includes = ["*.sh"]
