[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = false

[certificatesResolvers.lets-encrypt.acme]
  email = "ayatsfer@gmail.com"
#   storage = "acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]
