[log]
  level = "DEBUG"

[api]
  dashboard = true
  insecure = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.lets-encrypt.acme]
  email = "ayatsfer@gmail.com"
  storage = "/var/lib/traefik/acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]