default:
  @just --list

apply-role:
  vault write /auth/token/roles/nomad-cluster @nomad-cluster-role.json

apply-policy:
  vault policy write nomad-server nomad-server-policy.hcl

get-token:
  vault token create -policy nomad-server -period 72h -orphan