# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  distant = {
    pname = "distant";
    version = "v0.20.0";
    src = fetchFromGitHub {
      owner = "chipsenkbeil";
      repo = "distant";
      rev = "v0.20.0";
      fetchSubmodules = false;
      sha256 = "sha256-DcnleJUAeYg3GSLZljC3gO9ihiFz04dzT/ddMnypr48=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./distant-v0.20.0/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
}
