# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  distant-aarch64-linux = {
    pname = "distant-aarch64-linux";
    version = "v0.20.0";
    src = fetchurl {
      url = "https://github.com/chipsenkbeil/distant/releases/download/v0.20.0/distant-aarch64-unknown-linux-gnu";
      sha256 = "sha256-92CA33GY8lS4GOun/vbRRChrFbK0yS6iZOoOu21u7V4=";
    };
  };
  distant-x86_64-linux = {
    pname = "distant-x86_64-linux";
    version = "v0.20.0";
    src = fetchurl {
      url = "https://github.com/chipsenkbeil/distant/releases/download/v0.20.0/distant-x86_64-unknown-linux-gnu";
      sha256 = "sha256-Xhev3SLQ/1xrPL1vBimYbQ7VFog7BqUSXtm/+8pdjmM=";
    };
  };
}
